### ISSUE TITLE
Color of catagories

### ISSUE THREAD

**Issue by mlambert74** [IJMacD/newsmap-js#1]
Just wondering if someone can change the colors as they are very similar and tend to blend.

Apologies...not a coder but love this site!

Thank you.

**Comment by IJMacD** [comment]
Thanks for the feedback.

I agree the colour choice isn't ideal! In this version I wanted to emulate as closely as possible the original newsmap.jp right down to the colours.

In a future version I could allow customisation of the colour scheme/palette.

**Comment by mlambert74** [comment]
Hi Iain,
Thank you for the response.  You rock!
I'm not a code person but simply love this site...I use in my classes at school frequently.  If possible, it needs a stronger diversity of colors as we show the various interests from different countries.
Know you are busy and I'm not sure how

**Comment by IJMacD** [comment]
I know you said you weren't a coder but if you're able to come up with a set of hex colours, I'll include them in a future version of the app.

This file will help you to get started:
https://github.com/IJMacD/newsmap-js/blob/master/src/colours.js

**Comment by mlambert74** [comment]
Hi Iain,
Thank you...I owe you...at least a gift certificate for Amazon.com
Here are the colors:
FF0000  WorldFFFF00  Nation40FF00  Business00BFFF  Technology0000FF  EntertainmentFF00FF  SportsD8D8D8  ScienceFF0080  Health
Thank you!
Michael L.

**Comment by IJMacD** [comment]
Hey, if you check out the site now you should find the option to change the colour palette.

I've included your colour set as one of the choices.

Obviously I don't expect anything in return but if you're serious about making a donation, an Amazon giftcard would definitely be appreciated. (IJMacD@gmail.com) Don't feel obligated though!
