### ISSUE TITLE
https://newsmap.ijmacd.com/ not working

### ISSUE THREAD

**Issue by SRDay** [IJMacD/newsmap-js#49]
Site responds, but does not render/update correctly...
![Capture](https://github.com/IJMacD/newsmap-js/assets/147742728/65ce9e42-d475-4a2d-ac5b-1e6708475fe3)

Problem started earlier this week.

**Comment by SRDay** [comment]
No apology required!  Many of us owe you a debt of gratitude for resurrecting the Newsmap.jp concept.  

I'm sorry if I missed it, but have you considered inviting donations from users to help support the site?

**Comment by IJMacD** [comment]
Thanks for your kindness. I used to have donation links in the README but removed them because I felt awkward soliciting donations. But perhaps I'll reconsider including links in some places.

**Comment by ChrisMeli1964** [comment]
Do not feel awkward about reminding people that they should pay for value received. I am suffering withdrawal. Let your users know how they can help get the site up and running again.

**Comment by Eric-Ness** [comment]
I would like to 2nd reinstating donation link. I've been using some variation of the newsmap since the old http://newsmap.jp days. I've even coded a version myself but, your implementation is perfect and would love to help out.

**Comment by abcde2024** [comment]
i would be happy to donate if that could help. and thank you for making this available in the first place !

**Comment by datasafeinternationalOfficial** [comment]
This is so valuable and I'm lost without it.  +1 would dono to keep it alive.

**Comment by IJMacD** [comment]
I appreciate everyone's support. I have moved the backend to another server for now and tried to make better use of proxies. I hope service stability stays at the same level you have all come to expect. 

I have also restored the donation links in the app and in the README.

I will try to keep up active development and if there are any feature requests, please feel free to open GitHub issues for them.

**Comment by SRDay** [comment]
Once again, working well here.  Thanks, Iain!  Initial donation sent.

**Comment by IJMacD** [comment]
Thank you very to all those who have already donated. 

It means a lot that others appreciate my work and the donations certainly help to cover ongoing costs.

As always I appreciate any feedback on the project you may have - positive or negative.
