### ISSUE TITLE
Bad Gateway?

### ISSUE THREAD

**Issue by SRDay** [IJMacD/newsmap-js#51]
Related to the new server?
![Untitled](https://github.com/IJMacD/newsmap-js/assets/147742728/8ba53068-5271-4cde-ad8c-492ef9bb204a)

**Comment by IJMacD** [comment]
Yes 🙏 should be fixed now. Please update if you still encounter issues.

**Comment by SRDay** [comment]
Working well here again.  Thank you!

**Comment by IJMacD** [comment]
Seems to be fairly stable now. Re-open if there are still problems.
